# Generated by Django 4.1 on 2023-12-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("localizacao", "0002_alter_localizacao_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localizacao",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="localizacao",
            name="longitude",
        ),
        migrations.AddField(
            model_name="localizacao",
            name="cep",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Cep"
            ),
        ),
        migrations.AddField(
            model_name="localizacao",
            name="cidade",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Cidade"
            ),
        ),
        migrations.AddField(
            model_name="localizacao",
            name="complemento",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Complemento"
            ),
        ),
        migrations.AlterField(
            model_name="localizacao",
            name="endereco",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Endereço"
            ),
        ),
    ]
