# Generated by Django 4.1 on 2023-12-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("servico", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profissional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=20)),
                ("habilidades", models.JSONField()),
                ("servicosPrestados", models.ManyToManyField(to="servico.servico")),
            ],
        ),
    ]
