# Generated by Django 4.1 on 2023-12-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profissional", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profissional",
            options={
                "ordering": ["id"],
                "verbose_name": "Profissional",
                "verbose_name_plural": "Profissionais",
            },
        ),
        migrations.AlterField(
            model_name="profissional",
            name="habilidades",
            field=models.CharField(max_length=100),
        ),
    ]
