# Generated by Django 4.1 on 2023-12-12 23:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profissional", "0002_alter_profissional_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profissional",
            name="servicosPrestados",
        ),
    ]
