# Generated by Django 4.1 on 2023-12-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servico", "0003_alter_servico_categoria_alter_servico_descricao_and_more"),
        ("profissional", "0003_remove_profissional_servicosprestados"),
    ]

    operations = [
        migrations.AddField(
            model_name="profissional",
            name="servicosPrestados",
            field=models.ManyToManyField(to="servico.servico"),
        ),
    ]
