# Generated by Django 4.1 on 2023-12-14 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profissional", "0004_profissional_servicosprestados"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profissional",
            name="servicosPrestados",
        ),
    ]
