# Generated by Django 4.1 on 2023-12-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.CharField(max_length=3, verbose_name="Nota")),
                (
                    "comentario",
                    models.TextField(max_length=300, verbose_name="Comentario"),
                ),
                (
                    "usuarioCliente",
                    models.CharField(max_length=100, verbose_name="Telefone"),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "ordering": ["id"],
            },
        ),
    ]
