# Generated by Django 4.1 on 2023-12-14 20:27

from django.db import migrations, models
import servico.models


class Migration(migrations.Migration):
    dependencies = [
        ("avaliacao", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avaliacao",
            name="usuarioCliente",
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="avaliacao_servico",
            field=models.CharField(
                default="0", max_length=300, verbose_name=servico.models.Servico
            ),
        ),
    ]
