# Generated by Django 4.1 on 2023-12-14 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("avaliacao", "0003_alter_avaliacao_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avaliacao",
            options={
                "ordering": ["id"],
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
            },
        ),
    ]
