# Generated by Django 4.1 on 2023-12-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cliente", "0003_alter_cliente_options_remove_cliente_cpf_cliente_and_more"),
        ("avaliacao", "0004_alter_avaliacao_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacao",
            name="avaliacao_cliente",
            field=models.ManyToManyField(to="cliente.cliente"),
        ),
    ]
