# Generated by Django 4.1 on 2023-12-14 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("avaliacao", "0005_avaliacao_avaliacao_cliente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avaliacao",
            name="avaliacao_cliente",
        ),
    ]
